# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:latest
  working_directory: ~/project/repo

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
          - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - repo

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test && npx codecov

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - f4:67:c7:78:7e:41:42:dd:ef:24:63:eb:67:66:14:c0
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: yarn deploy

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - test:
          requires:
          - install

  install-and-deploy:
    jobs:
      - install
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: master
